--SQL Advance Case Study
select * from dim_manufacturer
select * from dim_model
select * from dim_customer
select * from dim_Location
select * from dim_date
select * from fact_transactions


--Q1--BEGIN
SELECT STATE 
FROM FACT_TRANSACTIONS T1
INNER JOIN DIM_LOCATION T2 ON T1.IDLOCATION= T2.IDLOCATION
INNER JOIN DIM_MODEL T3 ON T1.IDMODEL= T3.IDMODEL
WHERE Date BETWEEN '01-01-2015' AND GETDATE()

--Q1--END

--Q2--BEGIN

SELECT TOP 1 
STATE FROM DIM_LOCATION X
INNER JOIN FACT_TRANSACTIONS Y ON X.IDLOCATION=Y.IDLOCATION
INNER JOIN DIM_MODEL Z ON Y.IDMODEL = Z.IDMODEL
INNER JOIN DIM_MANUFACTURER W ON W.IDMANUFACTURER= Z.IDMANUFACTURER
WHERE MANUFACTURER_NAME = 'Samsung'
GROUP BY STATE
ORDER BY SUM(QUANTITY) DESC
	
--Q2--END

--Q3--BEGIN 
SELECT MODEL_NAME, ZIPCODE, STATE, COUNT(IDCUSTOMER) AS NO_OF_TRANSACTIONS FROM DIM_LOCATION
INNER JOIN FACT_TRANSACTIONS ON DIM_LOCATION.IDLOCATION=FACT_TRANSACTIONS.IDLOCATION
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
GROUP BY MODEL_NAME, ZIPCODE, STATE
	
--Q3--END

--Q4--BEGIN
SELECT TOP 1
IDMODEL, MODEL_NAME FROM DIM_MODEL
ORDER BY UNIT_PRICE
--Q4--END

--Q5--BEGIN
SELECT MODEL_NAME, AVG(UNIT_PRICE) AS AVG_PRICE FROM DIM_MODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
WHERE MANUFACTURER_NAME IN 
(
SELECT TOP 5 MANUFACTURER_NAME FROM FACT_TRANSACTIONS 
INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(QUANTITY)
)
GROUP BY MODEL_NAME
ORDER BY AVG(UNIT_PRICE) DESC

--Q5--END

--Q6--BEGIN

SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AVG_SPENT
FROM DIM_CUSTOMER
INNER JOIN FACT_TRANSACTIONS ON DIM_CUSTOMER.IDCUSTOMER = FACT_TRANSACTIONS.IDCUSTOMER
WHERE YEAR(Date) = 2009 
GROUP BY CUSTOMER_NAME
HAVING AVG(TOTALPRICE)>500

--Q6--END
	
--Q7--BEGIN
SELECT IDModel, Model_Name
from (
   SELECT Top 5 
      T.IDModel , Dim.Model_Name
   From FACT_TRANSACTIONS as T
   join DIM_DATE as D on T.DATE = D.DATE
   join DIM_MODEL as Dim on T.IDModel = Dim.IDModel
   where D.YEAR = 2008
   Group By T.IDModel, Dim.Model_Name
   order by SUM(Quantity) DESC ) as year_2008

   intersect

   SELECT IDModel, Model_Name
from (
   SELECT Top 5 
      T.IDModel , Dim.Model_Name
   From FACT_TRANSACTIONS as T
   join DIM_DATE as D on T.DATE = D.DATE
   join DIM_MODEL as Dim on T.IDModel = Dim.IDModel
   where D.YEAR = 2009
   Group By T.IDModel, Dim.Model_Name
   order by SUM(Quantity) DESC ) as year_2009

   intersect

   SELECT IDModel, Model_Name
from (
   SELECT Top 5 
      T.IDModel , Dim.Model_Name
   From FACT_TRANSACTIONS as T
   join DIM_DATE as D on T.DATE = D.DATE
   join DIM_MODEL as Dim on T.IDModel = Dim.IDModel
   where D.YEAR = 2010
   Group By T.IDModel, Dim.Model_Name
   order by SUM(Quantity) DESC ) as year_2010

--Q7--END	
--Q8--BEGIN

SELECT TOP 1 MANUFACTURER_NAME 
FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
GROUP BY MANUFACTURER_NAME
ORDER BY SUM(TOTALPRICE) DESC

--Q8--END

--Q9--BEGIN
	
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(Date) = 2010 
EXCEPT 
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(Date) = 2009

--Q9--END

--Q10--BEGIN

SELECT TOP 100 CUSTOMER_NAME, 
AVG(CASE WHEN YEAR(Date) = 2005 THEN TOTALPRICE END) as AVERAGE_PRICE_2005,
AVG(CASE WHEN YEAR(Date) = 2005 THEN QUANTITY END) as AVERAGE_QTY_2005,
AVG(CASE WHEN YEAR(Date) = 2018 THEN TOTALPRICE END) as AVERAGE_PRICE_2018,
AVG(CASE WHEN YEAR(Date) = 2018 THEN QUANTITY END) as AVERAGE_QTY_2018
FROM DIM_CUSTOMER
INNER JOIN FACT_TRANSACTIONS T1 ON T1.IDCUSTOMER= DIM_CUSTOMER.IDCUSTOMER
GROUP BY CUSTOMER_NAME

--Q10--END
	